exports.shorthands = undefined;
exports.up = (pgm) => {
  pgm.createTable('tickets', { id: { type: 'uuid', primaryKey: true }, category: { type: 'varchar(80)', notNull: true }, priority: { type: 'varchar(20)', notNull: true }, status: { type: 'varchar(30)', notNull: true, default: 'submitted' }, sensitivity: { type: 'varchar(20)', notNull: true, default: 'standard' }, queue: { type: 'varchar(80)', notNull: true }, branch_code: { type: 'varchar(30)', notNull: true }, department: { type: 'varchar(80)', notNull: true }, legal_entity: { type: 'varchar(50)', notNull: true }, country: { type: 'varchar(2)', notNull: true }, subject: { type: 'varchar(200)', notNull: true }, description: { type: 'text', notNull: true }, custom_fields: { type: 'jsonb', notNull: true, default: '{}' }, created_by: { type: 'varchar(160)', notNull: true }, assigned_to: { type: 'varchar(160)' }, created_at: { type: 'timestamptz', notNull: true, default: pgm.func('current_timestamp') }, updated_at: { type: 'timestamptz', notNull: true, default: pgm.func('current_timestamp') } });
  pgm.createIndex('tickets', ['queue', 'status']); pgm.createIndex('tickets', ['branch_code', 'created_at']);
  pgm.createTable('ticket_references', { id: { type: 'uuid', primaryKey: true }, ticket_id: { type: 'uuid', notNull: true, references: 'tickets', onDelete: 'restrict' }, reference_type: { type: 'varchar(40)', notNull: true }, source_system: { type: 'varchar(80)', notNull: true }, opaque_reference: { type: 'varchar(255)', notNull: true }, masked_value: { type: 'varchar(255)', notNull: true }, classification: { type: 'varchar(20)', notNull: true, default: 'confidential' } });
  pgm.createTable('idempotency_records', { actor_id: { type: 'varchar(160)', notNull: true }, idempotency_key: { type: 'varchar(128)', notNull: true }, request_hash: { type: 'varchar(64)', notNull: true }, response_ticket_id: { type: 'uuid', notNull: true, references: 'tickets' }, created_at: { type: 'timestamptz', notNull: true, default: pgm.func('current_timestamp') } });
  pgm.addConstraint('idempotency_records', 'idempotency_actor_key', { primaryKey: ['actor_id', 'idempotency_key'] });
  pgm.createTable('approval_requests', { id: { type: 'uuid', primaryKey: true }, ticket_id: { type: 'uuid', notNull: true, references: 'tickets' }, action_type: { type: 'varchar(80)', notNull: true }, requested_by: { type: 'varchar(160)', notNull: true }, status: { type: 'varchar(20)', notNull: true, default: 'pending' }, created_at: { type: 'timestamptz', notNull: true, default: pgm.func('current_timestamp') } });
  pgm.createTable('audit_events', { sequence: { type: 'bigserial', primaryKey: true }, id: { type: 'uuid', notNull: true, unique: true }, occurred_at: { type: 'timestamptz', notNull: true, default: pgm.func('current_timestamp') }, actor_id: { type: 'varchar(160)', notNull: true }, action: { type: 'varchar(100)', notNull: true }, target_type: { type: 'varchar(60)', notNull: true }, target_id: { type: 'varchar(160)', notNull: true }, correlation_id: { type: 'varchar(128)', notNull: true }, outcome: { type: 'varchar(20)', notNull: true }, metadata: { type: 'jsonb', notNull: true, default: '{}' }, previous_hash: { type: 'varchar(64)' }, event_hash: { type: 'varchar(64)', notNull: true } });
  pgm.createIndex('audit_events', ['target_type', 'target_id', 'occurred_at']);
};
exports.down = (pgm) => ['audit_events', 'approval_requests', 'idempotency_records', 'ticket_references', 'tickets'].forEach((table) => pgm.dropTable(table));
