import { createServer, type Server } from 'node:http';
import { Pool } from 'pg';
import { exportJWK, generateKeyPair, SignJWT, type JWK, type KeyLike } from 'jose';
import { Test } from '@nestjs/testing';
import { ValidationPipe } from '@nestjs/common';
import { FastifyAdapter, type NestFastifyApplication } from '@nestjs/platform-fastify';
import { AppModule } from '../src/app.module.js';
import { OutboxService } from '../src/outbox/outbox.service.js';

const run = process.env.RUN_DB_INTEGRATION === '1';
const describeIfDatabase = run ? describe : describe.skip;

describeIfDatabase('ticket lifecycle integration', () => {
  let app: NestFastifyApplication;
  let pool: Pool;
  let server: Server;
  let privateKey: KeyLike;
  let publicJwk: JWK;
  let issuer: string;
  const ticketIds: string[] = [];
  const configurationKeys: { queue: string; category: string }[] = [];
  const slaPolicyKeys: string[] = [];
  const templateKeys: string[] = [];

  beforeAll(async () => {
    process.env.DATABASE_URL ??= 'postgresql://case_user:case_password@localhost:5433/case_platform';
    const keys = await generateKeyPair('RS256'); privateKey = keys.privateKey; publicJwk = { ...(await exportJWK(keys.publicKey)), kid: 'integration-key', alg: 'RS256', use: 'sig' };
    server = createServer((request, response) => { if (request.url === '/jwks') { response.setHeader('content-type', 'application/json'); response.end(JSON.stringify({ keys: [publicJwk] })); return; } response.statusCode = 404; response.end(); });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    const address = server.address(); if (!address || typeof address === 'string') throw new Error('JWKS server did not start');
    issuer = `http://127.0.0.1:${address.port}/realms/integration`;
    process.env.OIDC_ISSUER = issuer; process.env.OIDC_AUDIENCE = 'bank-case-api'; process.env.OIDC_JWKS_URI = `http://127.0.0.1:${address.port}/jwks`;
    const module = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = module.createNestApplication<NestFastifyApplication>(new FastifyAdapter()); app.setGlobalPrefix('v1'); app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true })); await app.init(); await app.getHttpAdapter().getInstance().ready();
    pool = new Pool({ connectionString: process.env.DATABASE_URL });
  });

  afterAll(async () => {
    if (pool) { for (const ticketId of ticketIds) { await pool.query('DELETE FROM integration_receipts WHERE outbox_event_id IN (SELECT id FROM integration_outbox WHERE aggregate_id=$1 OR payload->>\'ticketId\'=$1)', [ticketId]); await pool.query('DELETE FROM integration_outbox WHERE aggregate_id=$1 OR payload->>\'ticketId\'=$1', [ticketId]); } for (const ticketId of ticketIds) { await pool.query('DELETE FROM ticket_relationships WHERE source_ticket_id=$1 OR target_ticket_id=$1', [ticketId]); await pool.query('DELETE FROM ticket_communications WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM ticket_retention_controls WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM attachments WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM ticket_notes WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM ticket_status_history WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM approval_requests WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM idempotency_records WHERE response_ticket_id=$1', [ticketId]); await pool.query('DELETE FROM ticket_references WHERE ticket_id=$1', [ticketId]); await pool.query('DELETE FROM tickets WHERE id=$1', [ticketId]); } for (const keys of configurationKeys) { await pool.query('DELETE FROM ticket_categories WHERE category_key=$1', [keys.category]); await pool.query('DELETE FROM case_queues WHERE queue_key=$1', [keys.queue]); } for (const policyKey of slaPolicyKeys) { await pool.query('DELETE FROM sla_policies WHERE policy_key=$1', [policyKey]); } for (const templateKey of templateKeys) { await pool.query('DELETE FROM communication_templates WHERE template_key=$1', [templateKey]); } await pool.end(); }
    if (app) await app.close(); await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
  });

  it('creates idempotent tickets, preserves masking, and records case activity', async () => {
    const agent = await token('case-agent'); const idempotencyKey = `integration-${Date.now()}`;
    const profile = await app.inject({ method: 'GET', url: '/v1/me', headers: auth(agent) }); expect(profile.statusCode).toBe(200); expect(profile.json()).toMatchObject({ roles: ['case-agent'], branch: 'BLR-01', legalEntity: 'BANK-IN', country: 'IN' });
    const queues = await app.inject({ method: 'GET', url: '/v1/configuration/queues', headers: auth(agent) }); expect(queues.statusCode).toBe(200); expect(queues.json().map((entry: { queue: string }) => entry.queue)).toEqual(['customer-support']);
    const categories = await app.inject({ method: 'GET', url: '/v1/configuration/categories', headers: auth(agent) }); expect(categories.statusCode).toBe(200); expect(categories.json().map((entry: { category: string }) => entry.category)).toEqual(['complaint', 'privacy-correction', 'service-request']);
    const payload = { category: 'service-request', priority: 'normal', sensitivity: 'standard', queue: 'customer-support', branchCode: 'BLR-01', department: 'operations', legalEntity: 'BANK-IN', country: 'IN', subject: 'Integration test case', description: 'Synthetic test data only', customFields: {}, references: [{ referenceType: 'customer', sourceSystem: 'CRM', opaqueReference: 'opaque-customer-1234' }] };
    const first = await app.inject({ method: 'POST', url: '/v1/tickets', headers: auth(agent, idempotencyKey), payload }); expect(first.statusCode).toBe(201); const created = first.json<{ id: string }>(); ticketIds.push(created.id);
    const retry = await app.inject({ method: 'POST', url: '/v1/tickets', headers: auth(agent, idempotencyKey), payload }); expect(retry.statusCode).toBe(201); expect(retry.json<{ id: string }>().id).toBe(created.id);
    const outbox = await pool.query<{ id: string; payload: Record<string, unknown> }>('SELECT id,payload FROM integration_outbox WHERE event_type=$1 AND aggregate_id=$2', ['ticket.created', created.id]); expect(outbox.rows).toHaveLength(1); expect(outbox.rows[0].payload).not.toHaveProperty('description'); expect(outbox.rows[0].payload).not.toHaveProperty('opaqueReference');
    // Other suites share this database and leave events behind; only this ticket's events matter for the dispatch assertions below.
    await pool.query("UPDATE integration_outbox SET status='published' WHERE status IN ('pending','retry','in_flight') AND COALESCE(payload->>'ticketId','') <> $1 AND aggregate_id <> $1", [created.id]);
    const publishedEvents: string[] = []; const dispatch = await app.get(OutboxService).processBatch({ publish: async (event) => { publishedEvents.push(event.eventType); } }); expect(dispatch.claimed).toBeGreaterThanOrEqual(1); expect(dispatch.published).toBe(dispatch.claimed); expect(publishedEvents).toContain('ticket.created');
    const deniedReceipt = await app.inject({ method: 'POST', url: `/v1/integrations/outbox/${outbox.rows[0].id}/receipts`, headers: auth(agent), payload: { externalSystem: 'CRM', externalReference: 'crm-event-1', outcome: 'accepted' } }); expect(deniedReceipt.statusCode).toBe(403);
    const receipt = await app.inject({ method: 'POST', url: `/v1/integrations/outbox/${outbox.rows[0].id}/receipts`, headers: auth(await token('integration-reconciler')), payload: { externalSystem: 'CRM', externalReference: 'crm-event-1', outcome: 'accepted', payloadHash: 'b'.repeat(64) } }); expect(receipt.statusCode).toBe(201); expect(receipt.json()).toMatchObject({ eventId: outbox.rows[0].id, externalSystem: 'CRM', outcome: 'accepted', replayed: false });
    const replayReceipt = await app.inject({ method: 'POST', url: `/v1/integrations/outbox/${outbox.rows[0].id}/receipts`, headers: auth(await token('integration-reconciler')), payload: { externalSystem: 'CRM', externalReference: 'crm-event-1', outcome: 'accepted', payloadHash: 'b'.repeat(64) } }); expect(replayReceipt.statusCode).toBe(201); expect(replayReceipt.json().replayed).toBe(true);
    const conflictingReceipt = await app.inject({ method: 'POST', url: `/v1/integrations/outbox/${outbox.rows[0].id}/receipts`, headers: auth(await token('integration-reconciler')), payload: { externalSystem: 'CRM', externalReference: 'crm-event-other', outcome: 'accepted', payloadHash: 'b'.repeat(64) } }); expect(conflictingReceipt.statusCode).toBe(409);
    const note = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/notes`, headers: auth(agent), payload: { visibility: 'internal', body: 'Synthetic internal note' } }); expect(note.statusCode).toBe(201);
    const communication = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/communications`, headers: auth(agent), payload: { channel: 'email', templateKey: 'ticket_acknowledgement', recipientReference: 'opaque-recipient-1234' } }); expect(communication.statusCode).toBe(201); expect(communication.json().status).toBe('queued'); expect(communication.json().recipientMasked).not.toBe('opaque-recipient-1234');
    const deniedDelivery = await app.inject({ method: 'POST', url: `/v1/integrations/communications/${communication.json().id}/receipts`, headers: auth(agent), payload: { provider: 'bank-email', providerMessageId: 'msg-1', status: 'sent' } }); expect(deniedDelivery.statusCode).toBe(403);
    const sentDelivery = await app.inject({ method: 'POST', url: `/v1/integrations/communications/${communication.json().id}/receipts`, headers: auth(await token('notification-provider')), payload: { provider: 'bank-email', providerMessageId: 'msg-1', status: 'sent' } }); expect(sentDelivery.statusCode).toBe(201); expect(sentDelivery.json()).toMatchObject({ communicationId: communication.json().id, status: 'sent', replayed: false });
    const replayDelivery = await app.inject({ method: 'POST', url: `/v1/integrations/communications/${communication.json().id}/receipts`, headers: auth(await token('notification-provider')), payload: { provider: 'bank-email', providerMessageId: 'msg-1', status: 'sent' } }); expect(replayDelivery.statusCode).toBe(201); expect(replayDelivery.json().replayed).toBe(true);
    const deliveredDelivery = await app.inject({ method: 'POST', url: `/v1/integrations/communications/${communication.json().id}/receipts`, headers: auth(await token('notification-provider')), payload: { provider: 'bank-email', providerMessageId: 'msg-1', status: 'delivered' } }); expect(deliveredDelivery.statusCode).toBe(201); expect(deliveredDelivery.json().status).toBe('delivered');
    const providerDeliveryEvents = await pool.query<{ event_type: string; payload: Record<string, unknown> }>('SELECT event_type,payload FROM integration_outbox WHERE aggregate_id=$1 AND event_type=$2', [communication.json().id, 'customer_communication.delivery_updated']); expect(providerDeliveryEvents.rows).toHaveLength(2); expect(JSON.stringify(providerDeliveryEvents.rows)).not.toContain('opaque-recipient-1234');
    const staleDelivery = await app.inject({ method: 'POST', url: `/v1/integrations/communications/${communication.json().id}/receipts`, headers: auth(await token('notification-provider')), payload: { provider: 'bank-email', providerMessageId: 'msg-1', status: 'failed', failureCode: 'late_failure' } }); expect(staleDelivery.statusCode).toBe(409);
    const approvalCommunication = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/communications`, headers: auth(agent), payload: { channel: 'email', templateKey: 'resolution_notice', recipientReference: 'opaque-recipient-5678' } }); expect(approvalCommunication.statusCode).toBe(201); expect(approvalCommunication.json().status).toBe('pending_approval'); expect(approvalCommunication.json().approvalId).toBeTruthy();
    const pendingEvent = await pool.query<{ event_type: string; payload: Record<string, unknown> }>('SELECT event_type,payload FROM integration_outbox WHERE aggregate_id=$1', [approvalCommunication.json().id]); expect(pendingEvent.rows[0].event_type).toBe('customer_communication.pending_approval'); expect(pendingEvent.rows[0].payload.status).toBe('pending_approval'); expect(pendingEvent.rows[0].payload).not.toHaveProperty('recipientReference'); expect(JSON.stringify(pendingEvent.rows[0].payload)).not.toContain('opaque-recipient-5678');
    const selfCommunicationDecision = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/approvals/${approvalCommunication.json().approvalId}/decision`, headers: auth(agent), payload: { decision: 'approved' } }); expect(selfCommunicationDecision.statusCode).toBe(403);
    const supervisorCommunicationDecision = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/approvals/${approvalCommunication.json().approvalId}/decision`, headers: auth(await token('supervisor')), payload: { decision: 'approved' } }); expect(supervisorCommunicationDecision.statusCode).toBe(201);
    const communicationStatus = await pool.query<{ status: string }>('SELECT status FROM ticket_communications WHERE id=$1', [approvalCommunication.json().id]); expect(communicationStatus.rows[0].status).toBe('queued');
    const deliveryEvent = await pool.query<{ event_type: string; payload: Record<string, unknown> }>('SELECT event_type,payload FROM integration_outbox WHERE aggregate_id=$1 AND event_type=$2', [approvalCommunication.json().id, 'customer_communication.queued']); expect(deliveryEvent.rows).toHaveLength(1); expect(JSON.stringify(deliveryEvent.rows[0].payload)).not.toContain('opaque-recipient-5678');
    const attachment = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/attachments`, headers: auth(agent), payload: { filename: '../statement.pdf', contentType: 'application/pdf', sizeBytes: 2048, classification: 'confidential' } }); expect(attachment.statusCode).toBe(201); expect(attachment.json()).toMatchObject({ uploadMethod: 'PUT', uploadStatus: 'pending_upload', malwareStatus: 'pending_scan', storageConfigured: false, uploadUrl: null }); const attachmentId = attachment.json<{ id: string }>().id;
    const completedAttachment = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/attachments/${attachmentId}/complete`, headers: auth(agent), payload: { checksumSha256: 'a'.repeat(64), sizeBytes: 2048 } }); expect(completedAttachment.statusCode).toBe(201); expect(completedAttachment.json().malwareStatus).toBe('pending_scan');
    const deniedDownload = await app.inject({ method: 'GET', url: `/v1/tickets/${created.id}/attachments/${attachmentId}/download`, headers: auth(agent) }); expect(deniedDownload.statusCode).toBe(409);
    const deniedScan = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/attachments/${attachmentId}/scan`, headers: auth(agent), payload: { result: 'clean' } }); expect(deniedScan.statusCode).toBe(403);
    const scan = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/attachments/${attachmentId}/scan`, headers: auth(await token('attachment-scanner')), payload: { result: 'clean' } }); expect(scan.statusCode).toBe(201); expect(scan.json().malwareStatus).toBe('clean');
    const cleanDownload = await app.inject({ method: 'GET', url: `/v1/tickets/${created.id}/attachments/${attachmentId}/download`, headers: auth(agent) }); expect(cleanDownload.statusCode).toBe(200); expect(cleanDownload.json()).toMatchObject({ attachmentId, storageConfigured: false, downloadUrl: null });
    const scanEvent = await pool.query<{ payload: Record<string, unknown> }>('SELECT payload FROM integration_outbox WHERE event_type=$1 AND aggregate_id=$2', ['attachment.scan_completed', attachmentId]); expect(scanEvent.rows).toHaveLength(1); expect(scanEvent.rows[0].payload).not.toHaveProperty('objectKey');
    const secondResponse = await app.inject({ method: 'POST', url: '/v1/tickets', headers: auth(agent, `${idempotencyKey}-related`), payload: { ...payload, subject: 'Related integration test case', references: [{ referenceType: 'customer', sourceSystem: 'CRM', opaqueReference: 'opaque-customer-9999' }] } }); expect(secondResponse.statusCode).toBe(201); const second = secondResponse.json<{ id: string }>(); ticketIds.push(second.id);
    const search = await app.inject({ method: 'GET', url: '/v1/tickets/search?q=Integration&limit=10', headers: auth(agent) }); expect(search.statusCode).toBe(200); expect(search.json().map((entry: { id: string }) => entry.id)).toEqual(expect.arrayContaining([created.id, second.id])); expect(JSON.stringify(search.json())).not.toContain('Synthetic test data only'); expect(JSON.stringify(search.json())).not.toContain('opaque-customer-1234');
    const agentHold = await app.inject({ method: 'PUT', url: `/v1/tickets/${created.id}/retention`, headers: auth(agent), payload: { legalHold: true, holdReason: 'Regulatory review', retentionUntil: '2030-01-01T00:00:00.000Z' } }); expect(agentHold.statusCode).toBe(403);
    const supervisorHold = await app.inject({ method: 'PUT', url: `/v1/tickets/${created.id}/retention`, headers: auth(await token('supervisor')), payload: { legalHold: true, holdReason: 'Regulatory review', retentionUntil: '2030-01-01T00:00:00.000Z' } }); expect(supervisorHold.statusCode).toBe(200); expect(supervisorHold.json()).toMatchObject({ ticketId: created.id, legalHold: true });
    const retentionEvent = await pool.query<{ payload: Record<string, unknown> }>('SELECT payload FROM integration_outbox WHERE event_type=$1 AND aggregate_id=$2', ['ticket.retention_control_updated', created.id]); expect(retentionEvent.rows[0].payload).not.toHaveProperty('holdReason');
    await pool.query("UPDATE tickets SET first_response_due_at=now()-interval '1 minute' WHERE id=$1", [created.id]);
    const deniedReconcile = await app.inject({ method: 'POST', url: '/v1/dashboard/sla/reconcile', headers: auth(agent) }); expect(deniedReconcile.statusCode).toBe(403);
    const reconcile = await app.inject({ method: 'POST', url: '/v1/dashboard/sla/reconcile', headers: auth(await token('supervisor')) }); expect(reconcile.statusCode).toBe(201); expect(reconcile.json().updated).toBeGreaterThanOrEqual(1); expect(reconcile.json().statuses.first_response_overdue).toBeGreaterThanOrEqual(1);
    const slaStatus = await pool.query<{ sla_status: string }>('SELECT sla_status FROM tickets WHERE id=$1', [created.id]); expect(slaStatus.rows[0].sla_status).toBe('first_response_overdue');
    const secondReconcile = await app.inject({ method: 'POST', url: '/v1/dashboard/sla/reconcile', headers: auth(await token('supervisor')) }); expect(secondReconcile.statusCode).toBe(201); expect(secondReconcile.json().updated).toBe(0);
    const relationship = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/relationships`, headers: auth(agent), payload: { targetTicketId: second.id, relationshipType: 'related_to' } }); expect(relationship.statusCode).toBe(201);
    const transition = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/status`, headers: auth(agent), payload: { toStatus: 'triage', reason: 'Initial review' } }); expect(transition.statusCode).toBe(201);
    const detail = await app.inject({ method: 'GET', url: `/v1/tickets/${created.id}`, headers: auth(agent) }); expect(detail.statusCode).toBe(200); expect(detail.json().references[0].maskedValue).toMatch(/•+1234$/); expect(detail.json().references[0].maskedValue).not.toBe('opaque-customer-1234'); expect(detail.json().notes).toHaveLength(1); expect(detail.json().communications).toEqual(expect.arrayContaining([expect.objectContaining({ templateKey: 'ticket_acknowledgement', status: 'delivered' }), expect.objectContaining({ templateKey: 'resolution_notice', status: 'queued', approvalId: approvalCommunication.json().approvalId })])); expect(detail.json().retention).toMatchObject({ legalHold: true }); expect(detail.json().attachments[0].filename).toBe('..statement.pdf'); expect(detail.json().attachments[0].malwareStatus).toBe('clean'); expect(detail.json().relatedTickets[0]).toMatchObject({ ticketId: second.id, relationshipType: 'related_to' }); expect(detail.json().slaPolicyKey).toBe('default'); expect(detail.json().resolutionDueAt).toBeTruthy();
    const deniedDashboard = await app.inject({ method: 'GET', url: '/v1/dashboard/summary', headers: auth(agent) }); expect(deniedDashboard.statusCode).toBe(403);
    const dashboard = await app.inject({ method: 'GET', url: '/v1/dashboard/summary', headers: auth(await token('supervisor')) }); expect(dashboard.statusCode).toBe(200); expect(dashboard.json().totals.total).toBeGreaterThanOrEqual(2); expect(dashboard.json().queues[0]).toHaveProperty('active');
    const reveal = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/sensitive-reveals`, headers: auth(agent) }); expect(reveal.statusCode).toBe(403);
    const audit = await pool.query<{ count: string }>('SELECT count(*) FROM audit_events WHERE target_id=$1', [created.id]); expect(Number(audit.rows[0].count)).toBeGreaterThanOrEqual(4);
    const deniedAudit = await app.inject({ method: 'GET', url: `/v1/audit/tickets/${created.id}`, headers: auth(agent) }); expect(deniedAudit.statusCode).toBe(403);
    const auditReport = await app.inject({ method: 'GET', url: `/v1/audit/tickets/${created.id}`, headers: auth(await token('auditor')) }); expect(auditReport.statusCode).toBe(200); expect(auditReport.json().events.length).toBeGreaterThanOrEqual(4); expect(JSON.stringify(auditReport.json())).not.toContain('opaque-customer-1234'); expect(JSON.stringify(auditReport.json())).not.toContain('Synthetic test data only');
    const auditExport = await app.inject({ method: 'GET', url: `/v1/audit/tickets/${created.id}/export?limit=200`, headers: auth(await token('auditor')) }); expect(auditExport.statusCode).toBe(200); expect(auditExport.json().exportedAt).toBeTruthy(); expect(auditExport.json().events.length).toBeGreaterThanOrEqual(4); expect(JSON.stringify(auditExport.json())).not.toContain('opaque-customer-1234'); expect(JSON.stringify(auditExport.json())).not.toContain('Synthetic test data only');
    const auditEvent = await pool.query<{ sequence: number }>('SELECT sequence FROM audit_events WHERE target_id=$1 ORDER BY sequence DESC LIMIT 1', [created.id]); await expect(pool.query('UPDATE audit_events SET action=$1 WHERE sequence=$2', ['tampered', auditEvent.rows[0].sequence])).rejects.toThrow('append-only');
  });

  it('rejects maker-checker self-approval and accepts an independent supervisor', async () => {
    const agent = await token('case-agent'); const supervisor = await token('supervisor'); const idempotencyKey = `approval-${Date.now()}`;
    const payload = { category: 'service-request', priority: 'normal', sensitivity: 'standard', queue: 'customer-support', branchCode: 'BLR-01', department: 'operations', legalEntity: 'BANK-IN', country: 'IN', subject: 'Approval integration case', description: 'Synthetic test data only', customFields: {}, references: [{ referenceType: 'customer', sourceSystem: 'CRM', opaqueReference: 'opaque-customer-5678' }] };
    const createdResponse = await app.inject({ method: 'POST', url: '/v1/tickets', headers: auth(agent, idempotencyKey), payload }); const created = createdResponse.json<{ id: string }>(); ticketIds.push(created.id);
    const approvalResponse = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/approvals`, headers: auth(agent), payload: { actionType: 'controlled-update' } }); expect(approvalResponse.statusCode).toBe(201); const approval = approvalResponse.json<{ id: string }>();
    const selfDecision = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/approvals/${approval.id}/decision`, headers: auth(agent), payload: { decision: 'approved' } }); expect(selfDecision.statusCode).toBe(403);
    const independentDecision = await app.inject({ method: 'POST', url: `/v1/tickets/${created.id}/approvals/${approval.id}/decision`, headers: auth(supervisor), payload: { decision: 'approved' } }); expect(independentDecision.statusCode).toBe(201);
    for (let attempt = 0; attempt < 5; attempt++) { await pool.query("UPDATE integration_outbox SET next_attempt_at=now() WHERE status IN ('pending','retry')"); await app.get(OutboxService).processBatch({ publish: async () => { throw new Error('synthetic publisher failure'); } }); }
    const deadLetters = await pool.query<{ count: string }>("SELECT count(*) FROM integration_outbox WHERE status='dead_letter' AND (aggregate_id=$1 OR payload->>'ticketId'=$1)", [created.id]); expect(Number(deadLetters.rows[0].count)).toBeGreaterThanOrEqual(1);
  });

  it('keeps configuration writes administrator-only and scoped', async () => {
    const queue = `integration-${Date.now()}`; const category = `${queue}-category`; configurationKeys.push({ queue, category });
    const agentAttempt = await app.inject({ method: 'PUT', url: `/v1/configuration/queues/${queue}`, headers: auth(await token('case-agent')), payload: { department: 'operations', legalEntity: 'BANK-IN', country: 'IN', active: true } }); expect(agentAttempt.statusCode).toBe(403);
    const admin = await token('administrator');
    const queueResponse = await app.inject({ method: 'PUT', url: `/v1/configuration/queues/${queue}`, headers: auth(admin), payload: { department: 'operations', legalEntity: 'BANK-IN', country: 'IN', active: true } }); expect(queueResponse.statusCode).toBe(200); expect(queueResponse.json()).toMatchObject({ queue, active: true });
    const categoryResponse = await app.inject({ method: 'PUT', url: `/v1/configuration/categories/${category}`, headers: auth(admin), payload: { defaultQueue: queue, active: true } }); expect(categoryResponse.statusCode).toBe(200); expect(categoryResponse.json()).toMatchObject({ category, defaultQueue: queue, active: true });
    const outbox = await pool.query<{ event_type: string }>('SELECT event_type FROM integration_outbox WHERE aggregate_id = ANY($1::text[])', [configurationKeys.flatMap((entry) => [entry.queue, entry.category])]); expect(outbox.rows.map((row) => row.event_type)).toEqual(expect.arrayContaining(['configuration.queue_changed', 'configuration.category_changed']));
    const policyKey = `integration-sla-${Date.now()}`; slaPolicyKeys.push(policyKey);
    const agentSla = await app.inject({ method: 'PUT', url: `/v1/configuration/sla/${policyKey}/normal`, headers: auth(await token('case-agent')), payload: { firstResponseMinutes: 60, resolutionMinutes: 600, active: true } }); expect(agentSla.statusCode).toBe(403);
    const adminSla = await app.inject({ method: 'PUT', url: `/v1/configuration/sla/${policyKey}/normal`, headers: auth(admin), payload: { firstResponseMinutes: 60, resolutionMinutes: 600, active: true } }); expect(adminSla.statusCode).toBe(200); expect(adminSla.json()).toMatchObject({ policyKey, priority: 'normal', firstResponseMinutes: 60, resolutionMinutes: 600 });
    const slaOutbox = await pool.query<{ event_type: string }>('SELECT event_type FROM integration_outbox WHERE aggregate_id=$1', [`${policyKey}:normal`]); expect(slaOutbox.rows[0].event_type).toBe('configuration.sla_policy_changed');
    const templates = await app.inject({ method: 'GET', url: '/v1/configuration/communication-templates', headers: auth(await token('case-agent')) }); expect(templates.statusCode).toBe(200); expect(templates.json()).toEqual(expect.arrayContaining([expect.objectContaining({ templateKey: 'ticket_acknowledgement', channel: 'email' })]));
    const templateKey = `integration-template-${Date.now()}`; templateKeys.push(templateKey);
    const agentTemplate = await app.inject({ method: 'PUT', url: `/v1/configuration/communication-templates/${templateKey}`, headers: auth(await token('case-agent')), payload: { channel: 'email', active: true, requiresApproval: true } }); expect(agentTemplate.statusCode).toBe(403);
    const adminTemplate = await app.inject({ method: 'PUT', url: `/v1/configuration/communication-templates/${templateKey}`, headers: auth(admin), payload: { channel: 'email', active: true, requiresApproval: true } }); expect(adminTemplate.statusCode).toBe(200); expect(adminTemplate.json()).toMatchObject({ templateKey, requiresApproval: true });
    const templateOutbox = await pool.query<{ event_type: string }>('SELECT event_type FROM integration_outbox WHERE aggregate_id=$1', [templateKey]); expect(templateOutbox.rows[0].event_type).toBe('configuration.communication_template_changed');
  });

  async function token(role: 'case-agent' | 'supervisor' | 'auditor' | 'administrator' | 'attachment-scanner' | 'integration-reconciler' | 'notification-provider'): Promise<string> { return new SignJWT({ roles: [role], branch: 'BLR-01', queues: ['customer-support'], department: 'operations', legal_entity: 'BANK-IN', country: 'IN' }).setProtectedHeader({ alg: 'RS256', kid: 'integration-key' }).setIssuer(issuer).setAudience('bank-case-api').setSubject(`${role}-${Math.random()}`).setIssuedAt().setExpirationTime('5m').sign(privateKey); }
  function auth(accessToken: string, idempotencyKey?: string): Record<string, string> { return { authorization: `Bearer ${accessToken}`, 'x-correlation-id': `integration-${Date.now()}`, ...(idempotencyKey ? { 'idempotency-key': idempotencyKey } : {}) }; }
});
